/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilUsuarioRouteImport } from './routes/perfilUsuario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport} from './routes/carrinho'

const PerfilUsuarioRoute = PerfilUsuarioRouteImport.update({
  id: '/perfilUsuario',
  path: '/perfilUsuario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/carrinho' : typeof CarrinhoRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/carrinho' : typeof CadastroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cadastro': typeof CadastroRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfilUsuario': typeof PerfilUsuarioRoute
  '/carrinho': typeof CarrinhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cadastro' | '/home' | '/login' | '/perfilUsuario' | '/carrinho'
  fileRoutesByTo: FileRoutesByTo
  to: '/cadastro' | '/home' | '/login' | '/perfilUsuario' | '/carrinho'
  id: '__root__' | '/cadastro' | '/home' | '/login' | '/perfilUsuario' | '/carrinho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CadastroRoute: typeof CadastroRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PerfilUsuarioRoute: typeof PerfilUsuarioRoute
  CarrinhoRoute: typeof CarrinhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfilUsuario': {
      id: '/perfilUsuario'
      path: '/perfilUsuario'
      fullPath: '/perfilUsuario'
      preLoaderRoute: typeof PerfilUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho',
      path: '/carrinho',
      fullpath: '/carrinho',
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CadastroRoute: CadastroRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PerfilUsuarioRoute: PerfilUsuarioRoute,
  CarrinhoRoute: CarrinhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
